#condense_wildcard_suffixes = true
#fn_single_line = true
#format_strings = true
#merge_imports = true
#normalize_comments = true
#normalize_doc_attributes = true
#reorder_impl_items = true
#version = "Two"
#wrap_comments = true
edition = "2018"
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true